### ISSUE TITLE
Question on PWP estimates

### ISSUE THREAD

**Issue by atcg** [petrelharp/tortoisescape#17]
When I use the formula for the weightings and PWP estimates from https://github.com/petrelharp/tortoisescape/blob/master/awkscripts/weighted-pwp.awk#L11 and https://github.com/petrelharp/tortoisescape/blob/master/awkscripts/weighted-pwp.awk#L13, I don't end up getting what I think are the right weighted pwp estimates for the self-self comparisons.

If I subtract the "-1" from each of lines 11 and 13, then I do get pretty much what I'm expecting. Meaning, changing those lines to this:

WW = D[N]*(D[N]) ;

and 

PI[N,N] += WW \* ( 2 \* P[N] \* ( D[N] - $(2*N-1) ) / (D[N]) ) ; # prob of difference

If I leave the "-1"s in there, it is inflating the estimates. For instance, I have a dataset where there are 10099 heterozygous sites in a 999990 bp genome, so I think the self-pwp estimate should be (10099/999990)*0.5=0.00504955. Instead it is 0.00518007. When I take out the "-1"s I get 0.00505056, a difference of 0.00000101 that I'm pretty sure is due to the effects of reduced coverage at the ends of this short genome.

Does that make any sense?

**Comment by petrelharp** [comment]
The estimator I was using is "the probability that two bases, chosen *without replacement*, differ."  As [in this writeup](https://github.com/petrelharp/tortoisescape/blob/1220699d3ded8912d0d8b0cef9bf46e830d475e8/awkscripts/weighted-pwp.awk#L11) if you've got n bases, k of which are A's and the rest T's; and you pick two of them at random, the chance they differ is k*(n-k)/(n*(n-1)); the "-1" on the bottom is for "without replacement".

If we did it *with* replacement, then we'd underestimate heterozygosity, since some of the comparisons we'd be making would be with the base itself.  As a simple example: suppose that we had coverage exactly 2 at all sites, and all sites are heterozygous.  Then say we sample a large number L of sites, of which L/2 have the same base seen two times; the remainder of which have different bases.

1. with replacement, the chance that you pick two different bases from (A,T) is 1/2, these are half the sites, so the estimate of heterozygosity is (1/2) * (1/2) = 1/4.
2. without replacement, the chance is 1 at those sites, so the the estimate of heterozygosity is (1/2) * 1 = 1/2, which is correct.

In your example, do you mean that there are 10099 *truly* heterozygous sites, from which you've sampled reads?  So you know the right answer should be 0.00504955?

Also: if you remove the "-1" from the weighting, then you're allowing it to use sites with coverage 1 to estimate heterozygosity, which doesn't make any sense.

Also also: note that the weightings cancels with the denominators, elimination of which would make the script much more efficient.

**Comment by atcg** [comment]
Correct on the example--there are 10099 truly heterozygous sites which I tiled reads across. More specifically, I have sampled reads from individual 1, which is homozygous to the reference for all reads. Then I've sampled reads from individual 2, which contains 10099 sites which are heterozygous with respect to the reference (reference is 999990bp long). So I think I should be getting the same estimates for the self-self comparison of individual 2 as I am getting for individual 2 to individual 1? But the self-self estimate is slightly higher (0.00518007 vs 0.00505058 or so).

Is the individual 1 to individual 2 comparison analogous to sampling with replacement? Should we not expect those two comparisons to give the same answer?

**Comment by atcg** [comment]
I should note that the difference between these two scenarios (self-self within heterozygous individual and comparison between heterozygous and homozygous individual) appears to be almost entirely due to the weightings being higher for the between individual comparison, which makes sense given that we're not subtracting 1 from one of the coverages in computing the locus weightings for between-individual comparisons.

Weightings for tortoise 0 and comparisonTortoise 0 : 1559300158.000000
PWP for tortoise 0 and comparisonTortoise 0 : 0.000000
Weightings for tortoise 1 and comparisonTortoise 0 : 1599286996.000000
PWP for tortoise 1 and comparisonTortoise 0 : 8077312.000000
Weightings for tortoise 1 and comparisonTortoise 1 : 1559300358.000000
PWP for tortoise 1 and comparisonTortoise 1 : 8077284.000000

**Comment by petrelharp** [comment]
Hm, ok.

Side note: we should really be adjusting our estimates of heterozygosity to
make them comparable to divergence. If there was no sequencing error, this
would mean multiplying by 2 (to account for the 50% of comparisons that
compare a chromosome with itself); otherwise, need to estimate sequencing
error and account for this.

Another side note: a possible estimator of sequencing error could be the
value that makes the correction above so that tortoise heterozygosity is
equal to mean divergence at distance zero; this makes assumptions, but
those might be reasonable.

Hm.  But, as for the original point, this calls for some simulations:
coming up.

**Comment by petrelharp** [comment]
I've run some simulation checks; see [this Rmd doc](https://github.com/petrelharp/tortoisescape/blob/b945d453b119c36e295c6a2da2fffb48ee77afe8/pairwisePi/pwp-method.Rmd), and let me know if it doesn't work for you?  (need to install `microbenchmark` for the timing comparison at the end)

(and edited the wrong bit in the previous comment)

**Comment by petrelharp** [comment]
You're right that the right answer for the comparison of the homozygous indiv to the heterozygous one should be the same as the heterozygosity of the other one.  (still, counterintuitively to me)

Can you run the sim a number of times (with fewer sites if it takes a while) to see if what you're seeing is sampling error?

**Comment by atcg** [comment]
Thanks for setting that up. I ran the simulations and it looks pretty clear that sampling with replacement underestimates the heterozygosities, which does make sense. I don't have any sequencing error in the versions I'm doing--I'm just trying to recover the (number of heterozygous sites / number of total sites) * 0.5, mostly to make sure converting things between text and binary is working, as well as the C++ heterozygosity/divergence calculation machinery. And there shouldn't be any variance in the example I'm running--the reads are spaced perfectly across the reference chromosomes (no sequencing errors, no read depth anomalies across the chromosomes).

What I don't quite get, though, is why the sum of the weightings across all sites aren't the same in the self-self vs intersample comparisons. In my examples I've got the same number of reads for sample 0 and sample 1. But the final weightings are higher in the intersample comparisons when we go to divide the sum of the pwp calculations by the sum of the weightings across loci because we're subtracting 1 from one of the sample coverages in computing the locus weightings in the self-self comparisons, but not in the inter-comparisons.

I understand we need to subtract 1 in the weighting function that is the first term in the probabilty calculation, but do we need to subtract 1 for calculating the global weightings that we'll divide by at the end? Meaning, change the self-self comparison section from lines 11 to 13 to this:

WW = D[N]*D[N] ; # This has changed to not subtracting 1 here
W[N,N] += WW ; # weights
PI[N,N] +=  (D[N]*(D[N]-1)) * ( 2 * P[N] * ( D[N] - $(2*N-1) ) / (D[N]-1) ) ; # This has changed by not using the WW calculation computed above, instead explicitly calculating (D[N]*(D[N]-1)) 

If I do that, then I get 0.00505057 for sample 1 to sample 0, and 0.00505055 for sample 1 to itself (which is ~ right).

Sidenote: I've got threading working in the C++ version--so it should be able to run on all sites in the genome in ~ 1 day.

**Comment by petrelharp** [comment]
Since there's no correlation between coverage and error or heterozygosity
here, changing the weights shouldn't affect things significantly.  (but, we
still don't know if the difference you are observing is significant
relative to sampling error??)  Looking at
```
nn <- 1:10
plot( nn^2/sum(nn^2) )
points( nn*(nn-1)/sum(nn*(nn-1)), col='red')
```
it looks like the weightings should be pretty much the same, except that
coverage=1 sites would count with the new weighting (and these are always
homozygous, so it's not suprising including these reduces divergence).
And, including coverage 1 sites is clearly not helpful for estimating
divergence.  Unless these are omitted, as in the R code, in which case it
shouldn't change things at all, really? (except for numerical error)  I
checked, in `pwp-method.Rmd` (pushed), and it doesn't.

Intuitively, we are counting each comparison of two different reads
equally; for comparing n reads to m reads there are n*m comparisons; for
comparing n reads to themselves there are n*(n-1) comparisons.

**Comment by atcg** [comment]
OK, revisiting this to make sure I have it right before starting new tort analyses.

Assume a single site with 100X coverage each for two tortoises. Tortoise A is heterozygous A/G (50 A reads and 50 G reads) and Tortoise B is homozygous G/G. Then, from https://github.com/petrelharp/tortoisescape/blob/master/awkscripts/weighted-pwp.awk:

- Tortoise A vs Tortoise A (which I believe should actually be 0.5):
weighting: 100 x (100-1) = 9900
pi = 9900 * (2 * .5 * (100 - (50)) / (99)) = 5000
Final (one-locus) printed result: 5000 / 9900 = 0.505050

- Tortoise A vs Tortoise B (which should also be 0.5):
weighting: 100 * 100 = 10000
pwp: 10000 * 0.5 * (1-1) + 1 * (1-.5) = 5000
Final (on-locus) printed result: 5000 / 10000 = 0.5

So I think the selfs are still off, but not because of the weightings, but because of the denominator in the pi calculation in line 13 of https://github.com/petrelharp/tortoisescape/blob/master/awkscripts/weighted-pwp.awk#L13. Is it possible that the denominator should just be D(N) instead of D(N) - 1?

**Comment by petrelharp** [comment]
Doing it the way we are doing it gets us an unbiased answer,
counterintuitively.  Note that the correct value for Tort A is actually 1,
not 1/2 (as would be pi between two homozygous torts with different
allleles).  We'd just multiply by 2 to get the right number, except for
sequencing error.

**Comment by petrelharp** [comment]
Yes; and I've checked by simulation that this gives us correct values here:

https://github.com/petrelharp/tortoisescape/blob/master/pairwisePi/pwp-method.html

**Comment by atcg** [comment]
OK, I guess I'm a little lost then as to why we obtain precisely the correct answer for a single locus at high depth for among-tortoise comparisons, whereas we do not for within-tortoise comparisons (always higher than 0.5, which needs to be multiplied by 2 as you say). And assuming perfectly even sequencing depth of the two alleles, why the values seem to be much larger for low depths (see attached)--is that not the bias you're referring to?

![selfpiatdiffcoverage](https://user-images.githubusercontent.com/2090981/40022605-5605ecbc-577d-11e8-882c-1fc30bf986d7.jpeg)

**Comment by petrelharp** [comment]
That's because to get the correct answer for within-individual comparisons
we'd need to know which reads came from the same chromosome and which did
not, and only compare the ones from different chromosomes.  Half of the
comparisons are "self" comparisons, so to get the right answer we should
just have to multiply by 2.  And, we should probably do this.  But, this
isn't quite right, because how errors enter is a bit different for within
versus between comparisons, IIRC.

**Comment by atcg** [comment]
OK, maybe I should just drop this, as I'm clearly missing something obvious. For a het site if the bases are different then don't we say they came from a diff chromosome (ignoring errors for now)?

But for a single site that is heterozygous with equal support for the two alleles, if the read depth is 2 then we get **1**, and if the read depth is 8 then we get **0.57**. Those are very different answers for exactly the same biological scenario where the only difference is read depth. I realize that there's a theoretical reason for having it in there, but if you remove the -1 from the denominator then the answer is always 0.5, which is exactly right and does not vary based on depth.

**Comment by petrelharp** [comment]
I'm not saying the current method is the best possible; but I am saying
that the method I'm proposing gives unbiased estimates, while the method
you are proposing gives biased estimates (counter-intuitively, I agree);
and that's shown in that document I made previously. We could gchat to talk
about what else to do if you like?

**Comment by atcg** [comment]
Ah, I get it now! You need to compensate for low-depth het sites where you don't sample both alleles by chance. Since this happens 50% of the time at depth=2, your het estimate has to be twice as high if you do happen to sample both alleles to average to 0.5. Thanks!
